[PHP]
post_max_size = 2G
upload_max_filesize = 2G
memory_limit = 500M
variables_order = EGPCS
fastcgi.logging = Off

; Error Reporting
display_errors = Off
log_errors = On
error_log = /var/log/php/error.log
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

; OPcache Settings
; opcache.enable = 1
; opcache.memory_consumption = 128
; opcache.interned_strings_buffer = 16
; opcache.max_accelerated_files = 10000
; opcache.validate_timestamps = 1
; opcache.revalidate_freq = 2
; opcache.fast_shutdown = 1
; opcache.enable_cli = 1
